### ISSUE TITLE
BallisticsManager: Move Update Logic Into Update Method

### ISSUE THREAD

**Issue by ZacharyPatten** [Kohana55/ConsoleInvaders#2]
# Info

You currently have a bug where the `BallisticManager.Projectiles` collection can be modified while you are inside `foreach` loops. It throws a `System.InvalidOperationException`. You can replicate this bug by pressing and holding the `[spacebar]` to rapid fire.

If you make the following two changes it will fix the bug for now, but it still isn't an ideal solution, I just wanted to provide you a quick fix to test:

[GameWorld.cs 149](https://github.com/Kohana55/ConsoleInvaders/blob/84d913741eb4b2ba92196774a16250540cbedfee/ConsoleInvaders/World/GameWorld.cs#L149)
```cs
// foreach (Projectile projectile in _ballisticManager.Projectiles)
foreach (Projectile projectile in _ballisticManager.Projectiles.ToArray())
```

[BallisticManager.cs 36](https://github.com/Kohana55/ConsoleInvaders/blob/84d913741eb4b2ba92196774a16250540cbedfee/ConsoleInvaders/World/BallisticManager.cs#L36)
```cs
// foreach (var projectile in Projectiles)
foreach (var projectile in Projectiles.ToArray())
```

# Solution

In order to properly fix the issue you need to move all logic regarding updating the ballistics into the `BallisticsManager.Update` method. For example, rather than adding projectiles in the `RegisterProjectile` method, you need to add them to a temporary queue that will be added inside the `Update` method the next time it runs.

**Comment by ZacharyPatten** [comment]
This issue also exists for other `foreach` loops. For example you can get an `IndexOutOfRangeException` in `GameWorld.cs line 141` (while looping) because the Invader is killed and its cell was updated (to an out of range value) while looping.

**Comment by Kohana55** [comment]
Will make those changes - I have started work on abstracting a lot of stuff out and this can be found on the Konsole Game Engine repo. 
Thanks for pointing out - I have removed any modification within loops of data stores.

**Comment by Kohana55** [comment]
The Git merge doesn't solve the issues pointed out but I am learning how to use the issue section of Git.
